language: c

cache:
  directories:
    - nim

env:
  global:
    - REPONAME="$(basename ${TRAVIS_BUILD_DIR})" # /travis/build/kaushalmodi/hello_musl -> hello_musl
    - NIMREPO="https://github.com/timotheecour/Nim"
    - NIMBRANCH="pr_fix_10030"
    - NIMVER="$(git ls-remote ${NIMREPO} ${NIMBRANCH} | cut -f 1)"
    - NIMDIR="${TRAVIS_BUILD_DIR}/nim/${NIMVER}"

install:
  # - find /usr/include -name "*.h" -print
  - echo "NIMDIR = ${NIMDIR}"
  - |
    if [[ ! -f "${NIMDIR}/bin/nim" ]]
    then
      rm -rf nim
      mkdir -p nim
      git clone --single-branch --branch ${NIMBRANCH} --depth=1 "${NIMREPO}" "${NIMDIR}"
      cd "${NIMDIR}" || exit
      sh build_all.sh
      # After building nim, wipe csources to save on cache space.
      rm -rf csources
    fi
  - export PATH="${NIMDIR}/bin:${PATH}"

script:
  - nim -v
  - |
    if [[ ! -f "${NIMDIR}/koch" ]]
    then
      echo "koch did not get built"
      exit 1
    fi

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
